language: python

python:
  - 3.4

env:
  - TOX_ENV=py27
  - TOX_ENV=py32
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=flake8

install:
  - pip install "tox>=2.3.1" "virtualenv<14.0.0"

script:
  - tox -e $TOX_ENV

after_success:
  - coverall
